### PR TITLE
Fix 0.4 deprecated bindings

### PR DESCRIPTION
**Pull request by yuyichao**
And upgrade travis settings.

### CODE REVIEW

**Comment by jwmerrill** [comment]
Really appreciate your help here. Looks like travis builds are failing on linux. It's trying to clone from the home folder for some reason.

**Comment by jwmerrill** [comment]
I'm a little out of the loop on the latest Travis developments. Where can I see what's supposed to happen with Travis when you specify Julia as the language? The travis file doesn't seem to specify much of anything anymore, so I assume we're just running with defaults that are set up somewhere else?

**Comment by jwmerrill** [comment]
Retest this please.

**Comment by jwmerrill** [comment]
> Retest this please.
Just to be clear, this was me trying to get Travis to automatically rerun the test. I'm not sure if that's even a think on Travis. I'm used to Jenkins.

**Comment by yuyichao** [comment]
You can do that by clicking the restart button on Travis.

Seems that git is still not happy. @tkelman .... If you are not too busy with the 0.4 and/or the win32 issue.

**Comment by jwmerrill** [comment]
I'm going to go ahead and merge this anyway, test infrastructure be damned. It's definitely a good change, and I want people to be able to use PowerSeries (and Roots, which depends on it) without warnings in 0.4.

**Comment by tkelman** [comment]
looks like it went away after merging, but as far as I know @timholy is the only other person who's seen that git fetch-pack error.

**Pull request merged**
