### PR TITLE
Update for Julia 1.0+

### PR DESCRIPTION
**Pull request by moble**
Updates infrastructure with standard github actions, basic structure for docs, modern Project.toml, etc.

Also, `gamma` and `polygamma` now appear in `SpecialFunctions.jl`, so I removed them here.

### CODE REVIEW

**Comment by jwmerrill** [comment]
This looks like good work. However, I haven't attempted to maintain this package for many years, and I don't have bandwidth (or, to be honest, interest) to think about maintaining it now.

I believe this package was delisted from the Julia package registry at some point. I think there may have been some kind of sweep of unmaintained packages before 1.0.

If you have a current use for this package, would you be interested in becoming its official owner? I think you could fork it and list your fork on the package registry. I'd be happy to archive this repo and point it at your fork if you're interested in that path.

One other thing to consider is whether [TaylorSeries.jl](https://github.com/JuliaDiff/TaylorSeries.jl) would meet your needs. That package has been more actively maintained.

**Comment by jwmerrill** [comment]
See https://github.com/jwmerrill/PowerSeries.jl/issues/7 for a discussion of the design tradeoffs for this package vs TaylorSeries.

**Comment by moble** [comment]
Sure, I'd be happy to take over maintenance.  (I don't have any particular plans for adding new features.)  If you're okay with it, I'll register my fork.

I did actually look into TaylorSeries, but there were some critical design features that this package had that were lacking in TaylorSeries, which made that not an option.

**Comment by jwmerrill** [comment]
> If you're okay with it, I'll register my fork.

That sounds good to me. Can you let me know when that's ready and I'll add some pointers from this repo to your fork?

**Pull request closed without merging**
